//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsOrders = new HashSet<ProductsOrders>();
        }
    
        public int Id { get; set; }
        public string Articule { get; set; }
        public int ProductNameId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public decimal Cost { get; set; }
        public int ManufacturerId { get; set; }
        public int ProviderId { get; set; }
        public int CategoryId { get; set; }
        public int Discount { get; set; }
        public int Count { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual ProductsNames ProductsNames { get; set; }
        public virtual Providers Providers { get; set; }
        public virtual Units Units { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsOrders> ProductsOrders { get; set; }



        public virtual string StringColor
        {
            get
            {
                string color = "White";


                if (Discount > 15)
                {
                    color = "#2E8B57";
                }

                if (Count == 0)
                {
                    color = "SkyBlue";
                }

                return color;
            }
        }

        public virtual string CostDiscount
        {
            get
            {
                decimal cost = Cost;
                int discount = Discount;
                string result = "";

                if (Discount > 0)
                {
                    result = (cost - (cost / 100 * Discount)).ToString() + " руб.";
                }

                return result;
            }
        }


        public virtual string ActualCostColor
        {
            get
            {
                string actualColor = "Black";

                if (Discount != 0)
                {
                    actualColor = "Red";
                }

                return actualColor;
            }
        }

        public virtual string TextDecoration
        {
            get
            {
                string actualTextDecoration = "None";

                if (Discount != 0)
                {
                    actualTextDecoration = "Strikethrough";
                }

                return actualTextDecoration;
            }
        }


        public virtual string Photo
        {
            get
            {
                if (string.IsNullOrEmpty(Image))
                    return System.IO.Path.GetFullPath("../../Resources/Images/picture.png");

                return System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ProductImages", Image);
            }
        }

    }
}
